### ISSUE TITLE
Bad configuration format: dh2066

### ISSUE THREAD

**Issue by DorianScholz** [coturn/coturn#550]
Looks like the example config file has not been updated to reflect "dh2066" now being the standard.

**Comment by misi** [comment]
Many thanks!

**Comment by Neustradamus** [comment]
@misi: It is solved now?

**Comment by OmlineEditor** [comment]
why size 2066 is used and not 2048? has always been the standard in other industries 2048.

**Comment by lonesomewalker** [comment]
Debian Bullseye still giving
```Bad configuration format: dh2066```

**Comment by bloodhunterd** [comment]
I cannot confirm that after removing the entry from the configuration file, the error still appears under Debian 11 (bullseye).

**Comment by OmlineEditor** [comment]
> I cannot confirm that after removing the entry from the configuration file, the error still appears under Debian 11 (bullseye).

show me what you changed and what mistake you have?

I do this, generate keys Diffie–Hellman:
`openssl dhparam -out  /var/lib/turn/dh-2048.pem 2048`

inside the configuration file **_/etc/turnserver.conf_**  I have it written like this
`dh-file=/var/lib/turn/dh-2048.pem`

**Comment by Neustradamus** [comment]
@ggarber: Can you look?

**Comment by eakraly** [comment]
Thanks @lonesomewalker and @bloodhunterd 
`--dh2066` is a non-existent configuration so it is expected to get an error.
