### ISSUE TITLE
TURN allocations over IPv6 return IPv6 allocations, even without keep-address-family

### ISSUE THREAD

**Issue by JonathanLennox** [coturn/coturn#598]
TURN allocation requests which do not specify a REQUESTED-ADDRESS-FAMILY attribute are supposed to be given IPv4 addresses, according to RFC 6156.

However, CoTurn does not do this for allocations made over IPv6, even when the --keep-address-family configuration parameter is not set.  In my testing, allocations made over IPv6 always return IPv6 allocations.

This means that an IPv6-only host (or a dual-stack host which happened to reach the coturn server over IPv6) cannot communicate with an IPv4-only host.

It appears this is because the `get_family` function in `ns_turn_server.c` returns the client connection's address family for `STUN_ATTRIBUTE_REQUESTED_ADDRESS_FAMILY_VALUE_DEFAULT`.

A workaround appears to be to explicitly set relay addresses.

**Comment by misi** [comment]
Thanks I will try to check it.

**Comment by misi** [comment]
@JonathanLennox  Sorry for my late reply. 
I have checked it on the latest master version and without REQUESTED-ADDRESS-FAMILY I  sent ALLOCATE request to (an IPv4 / IPv6 dual stack) a serverIPv6 address and it allocated an IPv4 address. So in the latest version it has been fixed or at least I couldn't reproduce it. Please comment this issue or open a new issue if you still experience it.

**Comment by yuanchieh-cheng** [comment]
I used 4.5.2 but still get the IPv6 address return without keep-address-family on server.  
I use `$ turnutils_uclient -T -n 2 -m 2 -l 100 -y -g  -x -u username -w password -v my-host` for test. It return `IPv6. Received relay addr:...`

**Comment by yuanchieh-cheng** [comment]
I found out this comment.  
It seems that If I don't write listening ip in the config, CoTURN would return ip based on client ip family, which is the same effect as "keep-address-family".
https://github.com/coturn/coturn/issues/217#issuecomment-407414379
