### ISSUE TITLE
0: ERROR: set_ctx: ERROR: cannot set DH

### ISSUE THREAD

**Issue by oguzhancelikarslan** [coturn/coturn#629]
getting this error and could not understand what it says. 
0: ERROR: set_ctx: ERROR: cannot set DH
0: DTLS1.2: Certificate file found: /etc/letsencrypt/live/xx.xxx.comfullchain.pem
0: DTLS1.2: Private key file found: /etc/letsencrypt/live/xx.xxx.com/privkey.pem

**Comment by onesse** [comment]
Same problem, do you have an explanation ?

**Comment by ngstwr** [comment]
Getting the same error! 
@oguzhancelikarslan Did you solve this?

**Comment by SharadKumar97** [comment]
Getting the same issue

**Comment by towynlin** [comment]
I'm also getting this same error. Here's a log snippet that happens on service start. I believe the pkey and cert are set up correctly. It's not obvious that these errors actually indicate that the server is having a problem. AFAICT my server is working just fine, but the errors are disconcerting.

```
0: Config file found: /usr/local/etc/turn_server_cert.pem
0: Config file found: /usr/local/etc/turn_server_pkey.pem
0: SSL23: ERROR: no certificate found
0: SSL23: Private key file found: /usr/local/etc/turn_server_pkey.pem
0: SSL23: ERROR: invalid private key
0: set_ctx: ERROR: cannot set DH
0: TLS1.0: ERROR: no certificate found
0: TLS1.0: Private key file found: /usr/local/etc/turn_server_pkey.pem
0: TLS1.0: ERROR: invalid private key
0: set_ctx: ERROR: cannot set DH
0: TLS1.1: ERROR: no certificate found
0: TLS1.1: Private key file found: /usr/local/etc/turn_server_pkey.pem
0: TLS1.1: ERROR: invalid private key
0: set_ctx: ERROR: cannot set DH
0: TLS1.2: ERROR: no certificate found
0: TLS1.2: Private key file found: /usr/local/etc/turn_server_pkey.pem
0: TLS1.2: ERROR: invalid private key
0: set_ctx: ERROR: cannot set DH
0: TLS cipher suite: DEFAULT
0: DTLS: ERROR: no certificate found
0: DTLS: Private key file found: /usr/local/etc/turn_server_pkey.pem
0: DTLS: ERROR: invalid private key
0: set_ctx: ERROR: cannot set DH
0: DTLS1.2: ERROR: no certificate found
0: DTLS1.2: Private key file found: /usr/local/etc/turn_server_pkey.pem
0: DTLS1.2: ERROR: invalid private key
0: set_ctx: ERROR: cannot set DH
0: DTLS cipher suite: DEFAULT
```

My server is ubuntu focal, using the apt package for 4.5.1.1 with security patches backported.
https://launchpad.net/ubuntu/+source/coturn/4.5.1.1-1.1ubuntu0.20.04.1
So probably this tag:
https://github.com/coturn/coturn/releases/tag/debian%2F4.5.1.1-1.1

Here are some links to the source code (at that tag) in `src/apps/relay/mainrelay.c` that outputs the errors:

- [no certificate found](https://github.com/coturn/coturn/blob/debian/4.5.1.1-1.1/src/apps/relay/mainrelay.c#L2767)
- [Private key file found](https://github.com/coturn/coturn/blob/debian/4.5.1.1-1.1/src/apps/relay/mainrelay.c#L2781)
- [invalid private key](https://github.com/coturn/coturn/blob/debian/4.5.1.1-1.1/src/apps/relay/mainrelay.c#L2785)
- [cannot set DH](https://github.com/coturn/coturn/blob/debian/4.5.1.1-1.1/src/apps/relay/mainrelay.c#L2895)

So...

- `SSL_CTX_use_certificate_chain_file()` is failing for some reason, then
- `SSL_CTX_use_PrivateKey_file()` does succeed, but
- `SSL_CTX_check_private_key()` fails, then
- the `dh` variable does successfully get set, possibly by `dh = get_dh1066()`, but
- `SSL_CTX_set_tmp_dh()` fails

Any maintainers or openssl experts have thoughts on this one?

**Comment by SharadKumar97** [comment]
Hi @towynlin 

Thanks for sharing the info. But i'm also getting Bind error where my coturn server is not starting and binding to the interface due this this DH error. Can you please share your turnserver.conf file ?

It will really help.

Thank you

**Comment by towynlin** [comment]
Sure thing — here it is with all the explanatory comments removed. When I put something in `ALL_CAPS` I have my own value there, and you should set yours.

```
external-ip=MY_SERVER_PUBLIC_IP
verbose
fingerprint
lt-cred-mech
user=MY_LONG_SECURE_USERNAME:MY_LONG_SECURE_PASSWORD
realm=SOMETHINGSOMETHING.COM
pkey-pwd=MY_LONG_SECURE_PKEY_PASSWORD
syslog
no-cli
cli-password=SOMETHING_JUST_TO_SILENCE_THE_LOG_ERROR
```

**Comment by terentev** [comment]
set
dh-file=/etc/letsencrypt/ssl-dhparams.pem

**Comment by fabifrank** [comment]
File was at a different location on my side:

```sh
$ sudo find / -name ssl-dhparams.pem
/usr/lib/python3/dist-packages/certbot/ssl-dhparams.pem
```

**Comment by SharadKumar97** [comment]
I fixed it. And I also got the permission issue on the latest coturn package.

**Comment by towynlin** [comment]
I notice that there are zero calls to `ERR_get_error()` or related error checking routines in `mainrelay.c`. That's the only way we can know for sure what's happening here.

**Comment by hekmon** [comment]
Or simply activate the `dh2066` config line if you do not want to use an external DH file.

**Comment by oxygen** [comment]
To generate a dh file using openssl:
`openssl dhparam -out dhparam4096.pem 4096`

**Comment by towynlin** [comment]
At least for me, generating a dh file with openssl and setting dh-file in the config got rid of this error. 👍 Didn't know I had to do that. TIL. 😁 

I still get the "no certificate found" and "invalid private key" errors as in my log snippet above, but that's a different issue. Thanks folks!

**Comment by misi** [comment]
Hello Guys! @towynlin @oxygen  @hekmon @SharadKumar97 @fabifrank @terentev @oguzhancelikarslan @ngstwr 

Sorry for my late response, I was busy with other projects.. :(

For me it is not clear what is the conclusion for this issue. 
Is there an error still exists that I need to fix? What was your solutions. 
Can you please help me to clarify and fix this issue? 
So do you still experience it with the latest 4.5.1.3 ? 
What was the issue, can you please explain it with full details? 

Thanks for you for your help and cooperation..

**Comment by SharadKumar97** [comment]
Hi @misi 

For me, it was a permission issue for version coturn 4.5.1.1-1.1ubuntu0.20.04.1
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=964009

I have not tested 4.5.13 but I think it should be working now.

**Comment by towynlin** [comment]
If generating a DH file is required to avoid this error, then that should be added to some getting started documentation. That's all I had to do to get rid of the error, but I didn't know it was necessary.

**Comment by misi** [comment]
@towynlin The generated DH file is not required by default as far as I experienced. 
I run Debian linux servers on without DH file with default settings and works properly. Is there any special in your config or environment?

**Comment by oxygen** [comment]
I think its required on Ubuntu 20.04.1. 
It wasn’t on Ubuntu 18.04.

It might not even have to do with coturn’s version.

**Comment by sdrhmn** [comment]
Thanks @terentev  @fabifrank 
This solved the issue for me. I get empty Domain name: 
How to fix that?

**Comment by rytisder** [comment]
Both of these are working - thanks 🙌 🚀 

https://github.com/coturn/coturn/issues/629#issuecomment-725543896

https://github.com/coturn/coturn/issues/629#issuecomment-729951345

**Comment by ChristianStornowski** [comment]
I'm getting this problem when using coturn with this configuration:

listening-port=3478
tls-listening-port=5349
listening-ip=0.0.0.0
listening-ip=::
external-ip=XXX.YYY.ZZZ.AAA
use-auth-secret
static-auth-secret=XXX
realm=domain
cert=/etc/ssl/certs/domain.with.root.pem
pkey=/etc/ssl/private/domain.key
cipher-list="HIGH"
ec-curve-name=secp384r1
syslog
no-cli
no-tlsv1
no-tlsv1_1

Why is SSL_CTX_set_tmp_dh used when using curves? Should SSL_CTX_set_tmp_ecdh be used instead?

**Comment by envdude** [comment]
Run this command: `openssl dhparam -out dhparam4096.pem 4096`

turnserver.conf 
```
istening-port=3478
fingerprint=True
use-auth-secret=True
static-auth-secret=<secret-key>
realm=domain.com
user-quota=100 #
total-quota=1200
no-tcp-relay
dh-file=/usr/local/etc/dhparam4096.pem
syslog
no-multicast-peers
cli-password = password
cert=/etc/coturn/certs/turn_server_cert.pem
pkey=/etc/coturn/certs/turn_server_pkey.pem
```
