### ISSUE TITLE
my two turnservers crashed with segfault

### ISSUE THREAD

**Issue by andyan-ai** [coturn/coturn#846]
I have an IM system and I set two turnservers to it for voip, one is main and another is slave, if the main server can't be connected then the IM will be used the slave.
But at last night, the two servers all crashed, the main's exception is:
Nov  1 22:27:25 i-1kg6l13w kernel: [11402857.061973] turnserver[28725]: segfault at 7f2484000080 ip 00007f2484000080 sp 00007f249ffee8d8 error 15
Nov  1 22:27:30 i-1kg6l13w systemd[1]: Stopping User Manager for UID 1000...
Nov  1 22:27:30 i-1kg6l13w systemd[28337]: Stopped target Default.
Nov  1 22:27:30 i-1kg6l13w systemd[28337]: Stopped target Basic System.
Nov  1 22:27:30 i-1kg6l13w systemd[28337]: Stopped target Paths.
Nov  1 22:27:30 i-1kg6l13w systemd[28337]: Stopped target Timers.
Nov  1 22:27:30 i-1kg6l13w systemd[28337]: Stopped target Sockets.
Nov  1 22:27:30 i-1kg6l13w systemd[28337]: Closed REST API socket for snapd user session agent.
Nov  1 22:27:30 i-1kg6l13w systemd[28337]: Closed GnuPG cryptographic agent (ssh-agent emulation).
Nov  1 22:27:30 i-1kg6l13w systemd[28337]: Closed GnuPG cryptographic agent and passphrase cache.
Nov  1 22:27:30 i-1kg6l13w systemd[28337]: Closed GnuPG network certificate management daemon.
Nov  1 22:27:30 i-1kg6l13w systemd[28337]: Closed GnuPG cryptographic agent and passphrase cache (access for web browsers).
Nov  1 22:27:30 i-1kg6l13w systemd[28337]: Closed GnuPG cryptographic agent and passphrase cache (restricted).
Nov  1 22:27:30 i-1kg6l13w systemd[28337]: Reached target Shutdown.
Nov  1 22:27:30 i-1kg6l13w systemd[28337]: Starting Exit the Session...
Nov  1 22:27:30 i-1kg6l13w systemd[28337]: Received SIGRTMIN+24 from PID 1455 (kill).
Nov  1 22:27:30 i-1kg6l13w systemd[1]: Stopped User Manager for UID 1000.
Nov  1 22:27:30 i-1kg6l13w systemd[1]: Removed slice User Slice of ubuntu.

the slave's exception is:
Nov  1 22:27:27 i-bm8a9od8 systemd[1]: Stopping User Manager for UID 1000...
Nov  1 22:27:27 i-bm8a9od8 systemd[24789]: Stopped target Default.
Nov  1 22:27:27 i-bm8a9od8 systemd[24789]: Stopped target Basic System.
Nov  1 22:27:27 i-bm8a9od8 systemd[24789]: Stopped target Timers.
Nov  1 22:27:27 i-bm8a9od8 systemd[24789]: Stopped target Sockets.
Nov  1 22:27:27 i-bm8a9od8 systemd[24789]: Closed REST API socket for snapd user session agent.
Nov  1 22:27:27 i-bm8a9od8 systemd[24789]: Closed GnuPG cryptographic agent (ssh-agent emulation).
Nov  1 22:27:27 i-bm8a9od8 systemd[24789]: Closed GnuPG cryptographic agent and passphrase cache.
Nov  1 22:27:27 i-bm8a9od8 systemd[24789]: Closed GnuPG cryptographic agent and passphrase cache (access for web browsers).
Nov  1 22:27:27 i-bm8a9od8 systemd[24789]: Closed GnuPG cryptographic agent and passphrase cache (restricted).
Nov  1 22:27:27 i-bm8a9od8 systemd[24789]: Stopped target Paths.
Nov  1 22:27:27 i-bm8a9od8 systemd[24789]: Closed GnuPG network certificate management daemon.
Nov  1 22:27:27 i-bm8a9od8 systemd[24789]: Reached target Shutdown.
Nov  1 22:27:27 i-bm8a9od8 systemd[24789]: Starting Exit the Session...
Nov  1 22:27:27 i-bm8a9od8 systemd[24789]: Received SIGRTMIN+24 from PID 20551 (kill).
Nov  1 22:27:27 i-bm8a9od8 systemd[1]: user@1000.service: Killing process 20551 (kill) with signal SIGKILL.
Nov  1 22:27:27 i-bm8a9od8 systemd[1]: Stopped User Manager for UID 1000.
Nov  1 22:27:27 i-bm8a9od8 systemd[1]: Removed slice User Slice of ubuntu.

I installed these two turnservers on "Ubuntu Server 18.04.5 LTS 64bit  | support IPv6" and the turnservers' version is Coturn-4.5.0.7 'dan Eider'

Why did this happen? 
thanks

**Comment by ggarber** [comment]
Is this still happening for you? Can you try with the latest version?

**Comment by anshuul-kai** [comment]
Same here. Crashing with a segfault with a very similar error message.

**Comment by eakraly** [comment]
@anshuul-kai pls provide more info so we can assist you: what version are you running? what OS?

**Comment by anshuul-kai** [comment]
My apologies for not including this in the original post @eakraly. It's the latest one available via apt on Ubuntu.

`4.5.0.7-1ubuntu2.18.04.3`

**Comment by eakraly** [comment]
Hi @anshuul-kai 
4.5.0 is *super* old version
You should manually build and run latest (4.6.2 at the moment) where a lot of crashes have been addressed

**Comment by anshuul-kai** [comment]
I'm working on this and will update the thread with my findings. Noticing one minor issue in the documentation for building. The clone command needs to change to the following.

`git clone https://github.com/coturn/coturn.git`

**Comment by anshul-kai** [comment]
Sorry about the delay in getting back @andyan-ai. It was quite painful to set this up as the only way to get this installed was by compiling from source which further required compiling other pre-requisites. I couldn't get all the dependencies on Ubuntu, CentOS and Amazon Linux but was finally able to get a build working on Amazon Linux 2. It still crashed with a segfault after running for a few hours.

What is the recommended OS to build this on and are there any plans to release the latest version via a package manager?

**Comment by eakraly** [comment]
@anshul-kai do you have any logs or dump files? Flow that caused the crash?

Also, Ubuntu 23.04/23.10 have coturn 4.6.1 that you can install from apt
